package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

type moduleInfo struct {
	Dir     string `json:"Dir"`
	Version string `json:"Version"`
}

func main() {
	outPath := flag.String("out", "icann_suffixes_gen.go", "output file path")
	flag.Parse()

	mod, err := loadModuleInfo()
	if err != nil {
		fail(err)
	}

	suffixes, err := extractICANNSuffixes(filepath.Join(mod.Dir, "publicsuffix", "table_test.go"))
	if err != nil {
		fail(err)
	}

	if err := writeGeneratedFile(*outPath, mod.Version, suffixes); err != nil {
		fail(err)
	}
}

func loadModuleInfo() (moduleInfo, error) {
	cmd := exec.Command("go", "list", "-m", "-json", "golang.org/x/net")
	output, err := cmd.Output()
	if err != nil {
		return moduleInfo{}, fmt.Errorf("load module info: %w", err)
	}

	var mod moduleInfo
	if err := json.Unmarshal(output, &mod); err != nil {
		return moduleInfo{}, fmt.Errorf("parse module info: %w", err)
	}
	if strings.TrimSpace(mod.Dir) == "" {
		return moduleInfo{}, fmt.Errorf("module dir missing for golang.org/x/net")
	}

	return mod, nil
}

func extractICANNSuffixes(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), 2*1024*1024)

	numICANNRules := -1
	inRules := false
	count := 0
	suffixes := make([]string, 0)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "const numICANNRules = ") {
			raw := strings.TrimPrefix(line, "const numICANNRules = ")
			value, err := strconv.Atoi(strings.TrimSpace(raw))
			if err != nil {
				return nil, fmt.Errorf("parse numICANNRules: %w", err)
			}
			numICANNRules = value
			continue
		}

		if line == "var rules = [...]string{" {
			inRules = true
			continue
		}

		if !inRules {
			continue
		}
		if line == "}" {
			break
		}
		if numICANNRules < 0 {
			return nil, fmt.Errorf("numICANNRules not found before rules table")
		}
		if count >= numICANNRules {
			break
		}

		count++
		ruleLiteral := strings.TrimSuffix(line, ",")
		rule, err := strconv.Unquote(ruleLiteral)
		if err != nil {
			return nil, fmt.Errorf("parse rule %q: %w", line, err)
		}
		if rule == "" || strings.HasPrefix(rule, "*.") || strings.HasPrefix(rule, "!") {
			continue
		}
		suffixes = append(suffixes, rule)
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan %s: %w", path, err)
	}
	if numICANNRules < 0 {
		return nil, fmt.Errorf("numICANNRules not found in %s", path)
	}

	return suffixes, nil
}

func writeGeneratedFile(outPath string, moduleVersion string, suffixes []string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	if moduleVersion != "" {
		buf.WriteString("// Source: golang.org/x/net/publicsuffix " + moduleVersion + "\n")
	}
	buf.WriteString("\npackage discovery\n\n")
	buf.WriteString("var icannExplicitSuffixes = []string{\n")
	for _, suffix := range suffixes {
		buf.WriteString("\t" + strconv.Quote(suffix) + ",\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	return nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
